<!-- 
  https://github.com/hojas/vue-mermaid-render
-->

<template>
  <pre 
    ref = "presentElem" 
    class = "mermaid" 
    v-html = "diagram_svg"
  ></pre>
</template>


<script setup lang="ts">

import { onMounted, ref, watchEffect, nextTick } from 'vue'

import type { MermaidConfig } from 'mermaid'
import mermaid from 'mermaid'

// console.log("$$$$ mermaid: " + JSON.stringify(mermaid, null, 2));   // !!

const props = defineProps<{
  config?: MermaidConfig            // 
}>()
console.log("$$$$ props: " + JSON.stringify(props));

const diagram_src = defineModel<string>("diagram_src", { local: true, default: "" });		// "\ngraph TD;\n  A-->B;\n  A-->C;\n  B-->D;\n  C-->D;\n"
const diagram_svg = defineModel<string>("diagram_svg", { local: true, default: "" });		// svg generated by mermaid.render(

const presentElem   = ref(null);    // 表示させる Html Tag
const mounted       = ref(false);   // 

function genSvgId() {
  const min = Math.ceil(1);
  const max = Math.floor(100000);
  const svgId = `mermaid-svg-${Math.floor(Math.random() * (max - min + 1))}${min}`;
  return svgId;                     // mermaid-svg-89921
}


async function updateGraph(graphDefinition: string) {               // graphDefinition: sequenceDiagram participant Alice ... 
  // console.log("$$$$ updateGraph ...........................");
  console.log("    graphDefinition: " + graphDefinition);         
  const id = genSvgId();                                            // mermaid-svg-89921
  console.log("    id: " + id);

  const res = await mermaid.render(id, graphDefinition, presentElem.value);  // .svg .bindFunctions ƒ(element)
  // console.log("    mermaid.render result: " + res);
  
  diagram_svg.value = res.svg;                                    // <svg aria-roledescription="sequence" ... 22.9 kB
  // console.log("    diagram_svg: " + diagram_svg.value);
}


watchEffect(() => {
  if (!mounted.value) {
    console.debug('Mermaid component not yet mounted');
    return
  }

  if (props.config) {
    console.log("$$$$ initialize mermaid widh config");
    mermaid.initialize({ startOnLoad: false, ...props.config });
  } else {
    console.log("$$$$ initialize mermaid without config");
    mermaid.initialize({ startOnLoad: false });
  }
})


watchEffect(() => {
  if (!mounted.value) {
    console.debug('Mermaid component not yet mounted');
    return
  }

  if (diagram_src.value)
    console.log("do updateGraph");
  updateGraph(diagram_src.value);
})


//=
onMounted(async () => { // after DOM nodes be inserted
  await nextTick();
  mounted.value = true
})

</script>


